### ISSUE TITLE
[Linux] AttributeError: Calling operator "bpy.ops.wm.console_toggle" error, could not be found

### ISSUE THREAD

**Issue by ghost** [Menithal/Blender-Hifi-Addon#20]
Traceback (most recent call last):
  File "/home/source/.config/blender/2.79/scripts/addons/hifi_tools/utils/custom.py", line 397, in execute
    return rename_bones_and_fix_most_things(self, context)
  File "/home/source/.config/blender/2.79/scripts/addons/hifi_tools/utils/custom.py", line 195, in rename_bones_and_fix_most_things
    bpy.ops.wm.console_toggle()
  File "/home/source/Blender/blender-2.79b-linux-glibc219-x86_64/2.79/scripts/modules/bpy/ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.wm.console_toggle" error, could not be found

location: <unknown location>:-1

**Comment by Menithal** [comment]
Thanks for pointing that out, This is caused by apparently by Blender not
filtering commands meant for Windows system (I thought it did this by
default, apparently it doesnt)

Unfortunately right now the Add-on is mostly focused on the Windows version
of the blender plugin, will make a fix later once I have the time to work
on the 2.8 update to make sure this doesnt occur on the Linux versions.

**Comment by Menithal** [comment]
This should be solved in the latest versions.
