### ISSUE TITLE
Errors when importing HF jsons into blender 2.81

### ISSUE THREAD

**Issue by Aitolda** [Menithal/Blender-Hifi-Addon#25]
Traceback (most recent call last):
  File "C:\Users\benbr\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\metaverse_tools\files\hifi_json\operator.py", line 187, in execute
    return load_file(self, context, **keywords)
  File "C:\Users\benbr\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\metaverse_tools\files\hifi_json\loader.py", line 39, in load_file
    scene = HifiScene(data, uv_sphere, join_children, merge_distance, delete_interior_faces, use_boolean_operation)
  File "C:\Users\benbr\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\metaverse_tools\hifi_world\scene.py", line 58, in __init__
    hifi_entity = HifiObject(entity, self)
  File "C:\Users\benbr\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\metaverse_tools\hifi_world\scene.py", line 177, in __init__
    (color['red'], color['green'], color['blue']))
  File "C:\Users\benbr\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\metaverse_tools\hifi_world\scene.py", line 121, in append_material
    mat.diffuse_color = tuple(c/255 for c in color)
ValueError: bpy_struct: item.attr = val: sequences of dimension 0 should contain 4 items, not 3

location: <unknown location>:-1

**Comment by Aitolda** [comment]
Seems to be fixed.
