### ISSUE TITLE
Error when converting MMD armature to HiFi

### ISSUE THREAD

**Issue by JulianGro** [Menithal/Blender-Hifi-Addon#34]
When converting an MMD armature to HiFi, the plugins finishes most of the work but throws an error:
```
Python: Traceback (most recent call last):
  File "/home/motofckr9k/.config/blender/2.91/scripts/addons/metaverse_tools/ui/modules/hifi.py", line 105, in execute
    mmd.convert_mmd_avatar_hifi()
  File "/home/motofckr9k/.config/blender/2.91/scripts/addons/metaverse_tools/utils/bones/mmd.py", line 469, in convert_mmd_avatar_hifi
    convert_bones(Translator, obj)
  File "/home/motofckr9k/.config/blender/2.91/scripts/addons/metaverse_tools/utils/bones/mmd.py", line 316, in convert_bones
    clean_up_bones(obj)
  File "/home/motofckr9k/.config/blender/2.91/scripts/addons/metaverse_tools/utils/bones/mmd.py", line 294, in clean_up_bones
    spine.select_set(state=True)
AttributeError: 'EditBone' object has no attribute 'select_set'

location: <unknown location>:-1
```

**Comment by dude22072** [comment]
Same issue here

```
Couldnt Detect Spine1, Creating Out of Spine2
Python: Traceback (most recent call last):
  File "C:\Users\josep\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\metaverse_tools\ui\modules\hifi.py", line 105, in execute
    mmd.convert_mmd_avatar_hifi()
  File "C:\Users\josep\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\metaverse_tools\utils\bones\mmd.py", line 469, in convert_mmd_avatar_hifi
    convert_bones(Translator, obj)
  File "C:\Users\josep\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\metaverse_tools\utils\bones\mmd.py", line 316, in convert_bones
    clean_up_bones(obj)
  File "C:\Users\josep\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\metaverse_tools\utils\bones\mmd.py", line 294, in clean_up_bones
    spine.select_set(state=True)
AttributeError: 'EditBone' object has no attribute 'select_set'

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\josep\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\metaverse_tools\ui\modules\hifi.py", line 105, in execute
    mmd.convert_mmd_avatar_hifi()
  File "C:\Users\josep\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\metaverse_tools\utils\bones\mmd.py", line 469, in convert_mmd_avatar_hifi
    convert_bones(Translator, obj)
  File "C:\Users\josep\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\metaverse_tools\utils\bones\mmd.py", line 316, in convert_bones
    clean_up_bones(obj)
  File "C:\Users\josep\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\metaverse_tools\utils\bones\mmd.py", line 294, in clean_up_bones
    spine.select_set(state=True)
AttributeError: 'EditBone' object has no attribute 'select_set'

location: <unknown location>:-1
```

**Comment by Menithal** [comment]
Thanks for reminiding me that I should look into it, I didnt update it yet to the 2.8x spec.
